src/OrderBundle/Entity/CreditRequest.php
<?php

namespace OrderBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * CreditRequest
 *
 * @ORM\Table(name="credit_request")
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 */
class CreditRequest
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="submit_date", type="datetime", nullable=true)
     */
    private $submitDate;

    /**
     * @var \AppBundle\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="creditRequestFor")
     * @ORM\JoinColumn(name="submitted_for_user_id", referencedColumnName="id")
     */
    private $submittedForUser;

    /**
     * @var \AppBundle\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="creditRequestBy")
     * @ORM\JoinColumn(name="submitted_by_user_id", referencedColumnName="id")
     */
    private $submittedByUser;

    /**
     * @ORM\ManyToOne(targetEntity="OrderBundle\Entity\Orders", inversedBy="creditRequest")
     * @ORM\JoinColumn(name="order_id", referencedColumnName="id")
     */
    private $order;

    /**
     * @ORM\ManyToOne(targetEntity="InventoryBundle\Entity\ProductVariant")
     * @ORM\JoinColumn(name="product_variant_id", referencedColumnName="id")
     */
    private $productVariant;

    /**
     * @var string
     *
     * @ORM\Column(name="comments", type="text", nullable=true)
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity="InventoryBundle\Entity\Channel", inversedBy="creditRequest")
     */
    private $channel;

    /**
     * @var float
     *
     * @ORM\Column(name="request_amount", type="integer")
     */
    private $requestAmount;
    /**
     * @var float
     *
     * @ORM\Column(name="applied_amount", type="integer")
     */
    private $appliedAmount = 0;


    /**
     * @var bool
     *
     * @ORM\Column(name="is_approved", type="boolean")
     */
    private $isApproved = false;

    /**
     * @ORM\PrePersist
     */
    public function setDate(){
        $this->setSubmitDate(new \DateTime());
    }


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return \AppBundle\Entity\User
     */
    public function getSubmittedForUser()
    {
        return $this->submittedForUser;
    }

    /**
     * @param \AppBundle\Entity\User $submittedForUser
     */
    public function setSubmittedForUser($submittedForUser)
    {
        $this->submittedForUser = $submittedForUser;
    }

    /**
     * @return \AppBundle\Entity\User
     */
    public function getSubmittedByUser()
    {
        return $this->submittedByUser;
    }

    /**
     * @param \AppBundle\Entity\User $submittedByUser
     */
    public function setSubmittedByUser($submittedByUser)
    {
        $this->submittedByUser = $submittedByUser;
    }

    /**
     * @return mixed
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * @param mixed $order
     */
    public function setOrder($order)
    {
        $this->order = $order;
    }

    /**
     * @return mixed
     */
    public function getProductVariant()
    {
        return $this->productVariant;
    }

    /**
     * @param mixed $product
     */
    public function setProductVariant($productVariant)
    {
        $this->productVariant = $productVariant;
    }

    /**
     * @return string
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @param string $comments
     */
    public function setComments($comments)
    {
        $this->comments = $comments;
    }

    /**
     * @return mixed
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * @param mixed $channel
     */
    public function setChannel($channel)
    {
        $this->channel = $channel;
    }

    /**
     * @return DateTime
     */
    public function getSubmitDate()
    {
        return $this->submitDate;
    }

    /**
     * @param DateTime $submitDate
     */
    public function setSubmitDate($submitDate)
    {
        $this->submitDate = $submitDate;
    }

    /**
     * @return mixed
     */
    public function getRequestAmount()
    {
        return $this->requestAmount/100;
    }

    /**
     * @param mixed $requestAmount
     */
    public function setRequestAmount($requestAmount)
    {
        $this->requestAmount = $requestAmount*100;
    }



    /**
     * Set isApproved
     *
     * @param boolean $isApproved
     *
     * @return CreditRequest
     */
    public function setIsApproved($isApproved)
    {
        $this->isApproved = $isApproved;

        return $this;
    }

    /**
     * Get isApproved
     *
     * @return boolean
     */
    public function getIsApproved()
    {
        return $this->isApproved;
    }

    /**
     * Set appliedAmount
     *
     * @param integer $appliedAmount
     *
     * @return CreditRequest
     */
    public function setAppliedAmount($appliedAmount)
    {
        $this->appliedAmount = $appliedAmount * 100;

        return $this;
    }

    /**
     * Get appliedAmount
     *
     * @return integer
     */
    public function getAppliedAmount()
    {
        return $this->appliedAmount/100;
    }

    public function getIdentifier() {
        return sprintf('CR-%s', str_pad($this->getId(), 5, 0, STR_PAD_LEFT));
    }
}

src/OrderBundle/Controller/API/LedgerController.php
<?php

namespace OrderBundle\Controller\API;

use Doctrine\DBAL\Types\DateType;
use OrderBundle\Services\LedgerService;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use OrderBundle\Entity\Ledger;
use OrderBundle\Form\CreditRequestType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\Encoder\JsonEncode;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * Office controller.
 *
 * @Route("/api")
 */
class LedgerController extends Controller
{
    /**
     * Creates a new ledger entry.
     *
     * @Route("/api_new_ledger", name="api_new_ledger")
     * @Method({"GET", "POST"})
     */
    public function newLedgerAction(Request $request)
    {
        $service = $this->get('ledger.service');

        try {
            $ledger = $service->newEntry(
                $request->get('amount'),
                $this->getDoctrine()
                    ->getRepository('AppBundle:User')
                    ->find($request->get('submittedForUserId')),
                $this->getUser(),
                $this->getDoctrine()
                    ->getRepository('InventoryBundle:Channel')
                    ->find($request->get('channelId')),
                $request->get('description'),
                $request->get('type'),
                $request->get('typeId'),
                true
            );
        } catch (\Exception $e) {
            return new JsonResponse("Error creating ledger entry: " . $e->getMessage(), 500);
        }

        return new JsonResponse($ledger);
    }
}

src/OrderBundle/Controller/LedgerController.php
<?php

namespace OrderBundle\Controller;

use Doctrine\DBAL\Types\DateType;
use InventoryBundle\Entity\Channel;
use InventoryBundle\Entity\PopItem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use OrderBundle\Entity\Ledger;
use OrderBundle\Form\CreditRequestType;
use OrderBundle\Form\CreditApprovalType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\Encoder\JsonEncode;
use Symfony\Component\Validator\Constraints\DateTime;
use OrderBundle\Form\NewCreditType;

/**
 * Ledger controller.
 *
 * @Route("/credits")
 */
class LedgerController extends Controller
{
    /**
     * Lists all Ledger entities if admin. Other roles can only see applicable ledgers
     *
     * @Route("/", name="ledger_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $ledgers = $em->getRepository('OrderBundle:Ledger')->findByUser($this->getUser());
//        $ledgers = $em->getRepository('OrderBundle:Ledger')->findBy(
//            array('user' => $this->getUser()),
//            array('channel' => $this->getUser()->getActiveChannel())
//        );
        $channel = $this->getUser()->getActiveChannel()->getName();

        return $this->render('@Order/Ledger/index.html.twig', array(
            'ledgers' => $ledgers,
            'user' => $this->getUser(),
            'channel' => $channel
        ));
    }

    /**
     * Creates a new credit request.
     *
     * @Route("/{id}/new", name="ledger_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request, Channel $channel)
    {
        $ledger = new Ledger();
        $form = $this->createForm(CreditRequestType::class, $ledger);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $em = $this->getDoctrine()->getManager();
                //add info that the form doesn't have
//                if(!$ledger->getSubmittedForUser())
                $ledger->setSubmittedForUser($this->getUser());
                $ledger->setSubmittedByUser($this->getUser());
                $ledger->setAchRequested(false);
                $ledger->setAmountCredited($ledger->getAmountRequested());
                $ledger->setDatePosted(new \DateTime());
                $ledger->setChannel($channel);
                $ledger->setType(Ledger::TYPE_LEDGER);
                //add the opposite side of the relations
                $ledger->getSubmittedForUser()->getLedgers()->add($ledger);
                $this->getUser()->getSubmittedLedgers()->add($ledger);
                $channel->getLedgers()->add($ledger);
                $em->persist($ledger);
                $em->flush();
            }
            catch(\Exception $e) {
                $this->addFlash('error', 'Error creating payment request entry: ' . $e->getMessage());
                return $this->render('@Order/Ledger/new.html.twig', array(
                    'ledger' => $ledger,
                    'channel' => $channel,
                    'form' => $form->createView(),
                ));
            }

            $this->addFlash('notice', 'Payment request created.');
            return $this->redirectToRoute('ledger_index');
        }

        return $this->render('@Order/Ledger/new.html.twig', array(
            'ledger' => $ledger,
            'channel' => $channel,
            'form' => $form->createView()
        ));
    }

    /**
     * Dislays form for admin to distribute credits to retailers and distributors
     *
     * @Route("/{id}/new/credit", name="ledger_credit_new")
     * @Method({"GET", "POST"})
     */
    public function newCreditAction(Request $request, Channel $channel)
    {
        $ledger = new Ledger();
        $form = $this->createForm(NewCreditType::class, $ledger);
        $form->handleRequest($request);

        $pop_item = new PopItem();

        //$pop_item->getWarehouses()->remove($warehouse);

        if ($form->isSubmitted() && $form->isValid())
        {
            try{
                $em = $this->getDoctrine()->getManager();

                $ledger->setSubmittedByUser($this->getUser());
                $ledger->setAchRequested(false);
                $ledger->setAmountCredited($ledger->getAmountRequested());
                $ledger->setCreditedByUser($this->getUser());
                $ledger->setDatePosted(new \DateTime());
                $ledger->setChannel($channel);
                $ledger->getSubmittedForUser()->getLedgers()->add($ledger);
                $ledger->setIsApproved(true);
                $channel->getLedgers()->add($ledger);
                $em->persist($ledger);
                $em->flush();
            }
            catch(\Exception $e)
            {
                $this->addFlash('error', 'Error creating credit request entry: ' . $e->getMessage());
                return $this->render('@Order/AddCredit/new.html.twig', array(
                    'ledger' => $ledger,
                    'channel' => $channel,
                    'form' => $form->createView(),
                ));
            }

            $this->addFlash('notice', 'Credit request created.');
            return $this->redirectToRoute('ledger_index');
        }

        return $this->render('@Order/AddCredit/new.html.twig' , array(
            'ledger' => $ledger,
            'channel' =>$channel,
            'form' => $form->createView()
        ));
    }


    /**
     * Displays a form to edit an existing credit request.
     *
     * @Route("/{id}/edit", name="ledger_edit")
     * @Method({"GET", "POST", "PATCH"})
     */
    public function editAction(Request $request, Ledger $ledger)
    {
        $deleteForm = $this->createDeleteForm($ledger);
        $editForm = $this->createForm(CreditRequestType::class, $ledger, array('method' => 'PATCH'));
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            try {
                $em = $this->getDoctrine()->getManager();
                $em->persist($ledger);
                $em->flush();
            }
            catch(\Exception $e) {
                $this->addFlash('error', 'Error updating credit request entry: ' . $e->getMessage());
                return $this->render('@Order/Ledger/edit.html.twig', array(
                    'ledger' => $ledger,
                    'edit_form' => $editForm->createView(),
                ));
            }

            $this->addFlash('notice', 'Credit request updated.');
            return $this->redirectToRoute('ledger_index');
        }

        return $this->render('@Order/Ledger/edit.html.twig', array(
            'ledger' => $ledger,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Shows admins credit requests so they can approve or deny them.
     *
     * @Route("/{id}", name="ledger_show")
     * @Method({"GET", "POST"})
     */
    public function showAction(Request $request, Ledger $ledger)
    {
        $form = $this->createForm(CreditApprovalType::class, $ledger);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $em = $this->getDoctrine()->getManager();
                $ledger->setCreditedByUser($this->getUser());
                $this->getUser()->getCreditedLedgers()->add($ledger);
                $ledger->setDatePosted(new \DateTime());
                $ledger->setIsArchived(true);
                $em->persist($ledger);
                $em->flush();
            }
            catch(\Exception $e) {
                $this->addFlash('error', 'Error updating credit request entry: ' . $e->getMessage());
                return $this->render('@Order/Ledger/show.html.twig', array(
                    'ledger' => $ledger,
                    'form' => $form->createView(),
                ));
            }

            $this->addFlash('notice', 'Credit posted.');
            return $this->redirectToRoute('ledger_index');
        }

        return $this->render('@Order/Ledger/show.html.twig', array(
            'ledger' => $ledger,
            'form' => $form->createView()
        ));
    }

    /**
     * Deletes a Ledger entity.
     *
     * @Route("/{id}", name="ledger_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, Ledger $ledger)
    {
        $form = $this->createDeleteForm($ledger);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $em = $this->getDoctrine()->getManager();
                $em->remove($ledger);
                $em->flush();
                $this->addFlash('notice', 'Ledger removed.');
            }
            catch(\Exception $e) {
                $this->addFlash('error', 'Error removing ledger entry: ' . $e->getMessage());
            }
        }

        return $this->redirectToRoute('ledger_index');
    }

    /**
     * Creates a form to delete a Ledger entity.
     *
     * @param Ledger $ledger The Ledger entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Ledger $ledger)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('ledger_delete', array('id' => $ledger->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/OrderBundle/Resources/views/Ledger/edit.html.twig
{% extends ':default:layout.html.twig' %}

{% block title %}Edit Credit Request{% endblock %}
{% block page_title %}
    Edit Credit Request
{% endblock page_title %}

{% block page_name %}
    <a href="{{ path('ledger_index') }}">< Back to the list</a>
{% endblock page_name %}

{% block actions %}
{% endblock actions %}

{% block footer %}
    <script>
        $(document).ready(function () {
            $('#charNum').text(255 - $('#ledger_description').val().length);
            $('#ledger_description').keyup(function () {
                var len = $(this).val().length;
                if (len >= 255) {
                    $(this).val($(this).val().substring(0, 255));
                    $('#charNum').text(0);
                } else {
                    var l = 255 - len;
                    $('#charNum').text(l);
                }
            });
        });
    </script>
{% endblock footer %}

{% block content %}
    {% if not edit_form.vars.valid %}
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">
                    {{ form_errors(edit_form.submittedForUser) }}
                    {{ form_errors(edit_form.amount) }}
                    {{ form_errors(edit_form.description) }}
                </div>
            </div>
        </div>
    {% endif %}
    <div class="table">
        <div class="form-body">
            {{ form_start(edit_form, {'attr': { 'class': 'form-horizontal' } }) }}
            <div class="row">
                <div class="col-md-4 form-group">
                    {{ form_label(edit_form.amountRequested) }}
                    {{ form_widget(edit_form.amountRequested) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 form-group">
                    {{ form_label(edit_form.description) }} <span id="charNum" style="font-weight:200;color:#8e8e8e;">255</span>
                    {{ form_widget(edit_form.description) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    {{ form_label(edit_form.phone) }}
                    {{ form_widget(edit_form.phone) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    {{ form_label(edit_form.email) }}
                    {{ form_widget(edit_form.email) }}
                </div>
            </div>
            {% if ledger.isArchived %}
                <br><strong>You may not edit a credit request that has been processed.</strong>
            {% else %}
                <input class="btn btn-raised btn-success" type="submit" value="Update" />
            {% endif %}
            {{ form_end(edit_form) }}
        </div>
    </div>
{% endblock %}

src/OrderBundle/Resources/views/Ledger/index.html.twig
{% extends ":default:layout.html.twig" %}

{% block title %}Ledger{% endblock %}
{% block page_title %}
    Ledger
{% endblock page_title %}

{% block page_name %}
    Listings
{% endblock page_name %}

{% block actions %}
{% endblock actions %}

{% block footer %}
    <script>
        $(document).ready(function () {
            var table = $('#part-table').DataTable({
                "iDisplayLength": 50, responsive: true, "fnDrawCallback": function(oSettings) {if (oSettings._iDisplayLength > oSettings.fnRecordsDisplay()) {$(oSettings.nTableWrapper).find('.dataTables_paginate').hide();}}, order: [[ 2, "desc" ]] });

            //hide the full description
            table.on('click', 'td#description', function () {
                var tr = $(this).parents('tr');
                var row = table.row( tr );
                var expanded = tr.attr('data-description-expanded');

                if (expanded == 1) {
                    tr.attr('data-description-expanded', 0);
                    // This row is already open - close it
                    row.child.hide();
                    tr.removeClass('shown');
                    $(this).closest('td').find('span').html('Click to expand');
                }
                else {
                    tr.attr('data-description-expanded', 1);
                    // Open this row (the format() function would return the data to be shown)
                    row.child(format(tr.data('child-value'), row.index()), "child").show();
                    $(this).closest('td').find('span').html('Click to collapse');
                    tr.addClass('shown');
                }

            });
            //put the description info in the child if table is in responsive mode
            table.on('responsive-display', function (e, datatable, row, showHide, update) {
//                console.log( 'Details for row '+row.index()+' '+(showHide ? 'shown' : 'hidden') );
                var info = $(row.node()).data('child-value');
                //hide expanded descriptions if shown
                if(row.child().isShown())
                    row.child().hide();
                if(showHide)
                    $(row.child()).find('span.dtr-data span').html(info);
                else
                    $(row.child()).find('span.dtr-data span').html('Click to expand');
            });
        });

        function format(description, index) {
            return '<ul data-dtr-index="'+index+'">' +
                    '<li data-dtr-index="'+index+'" data-dt-row="'+index+'" data-dt-column="9">' +
                    '<span class="dtr-title">Description</span>&nbsp;' +
                    '<span class="dtr-data"><span>'+description+'</span></span></li></ul>';
        }

        function createLedgerWithAPI(amount, submittedForUserId, channelId, description, type, typeId) {
            $.ajax({
                type: 'POST',
                url: "{{ path('api_new_ledger') }}",
                dataType: 'json',
                data: {amount: amount, submittedForUserId: submittedForUserId, channelId: channelId, description: description, type: type, typeId: typeId},
                success: function (data) {
//                    console.log(JSON.stringify(data,null,4));
                }
            });
        }
    </script>
{% endblock footer %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="table">
                <table id="part-table" class="table table-striped table-bordered dataTable no-footer" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Type</th>
                        <th>Amount</th>
                        <th>Date Created</th>
                        {% if app.user.hasRole('ROLE_ADMIN') %}
                            <th>Submitted by</th>
                            <th>On Behalf of</th>
                        {% endif %}
                        {#<th>ACH</th>#}
                        <td>Source</td>
                        <th>Description</th>
                        {% if app.user.hasRole('ROLE_ADMIN') %}
                            {#<th>ACH STATUS</th>#}
                            <th>Actions</th>
                        {% endif %}

                    </tr>
                    </thead>
                    <tbody>
                    {% for ledger in ledgers %}
                        {% if ledger.channel.name == channel %}
                        <tr data-child-value="{{ ledger.description | default('') }}" data-description-expanded="0">
                            <td>{{ ledger.type }}</td>
                            {% if ledger.amountCredited >= 0 %}
                                <td>${{ ledger.amountCredited | number_format(2) }}</td>
                            {% else %}
                                <td>$<span style="color:red">{{ ledger.amountCredited | number_format(2) }}</span></td>
                            {% endif %}
                            <td>{{ ledger.dateCreated | date('m/d/y') }}</td>
                            {% if app.user.hasRole('ROLE_ADMIN') %}
                                <td>{{ ledger.submittedByUser.fullName | default('--') }}</td>
                                <td>{{ ledger.submittedForUser.fullName | default('--') }}</td>
                            {% endif %}

                            <td>
                                {% if ledger.creditRequest %}{{ ledger.creditRequest.identifier }}{% endif %}
                                {% if ledger.warrantyClaim %}{{ ledger.warrantyClaim.identifier }}{% endif %}
                                {% if ledger.rebateSubmission %}{{ ledger.rebateSubmission.identifier }}{% endif %}
                                {% if ledger.order %}{{ ledger.order.identifier }}{% endif %}
                            </td>

                            {#<td>{% if ledger.achRequested %}Yes{% else %}No{% endif %}</td>#}
                            <td id="description">{% if ledger.description is not null %}<span>Click to expand</span>{% else %}--{% endif %}</td>
                            
                            {% if app.user.hasRole('ROLE_ADMIN') %}

                                <td>
                                    {% if ledger.type|upper == 'LEDGER"' %}{{ ledger.achRequested  ? "SENT" : "PENDING" }}{% endif %}
                                {% if ledger.type|upper == 'LEDGER' and not ledger.achRequested %}
                                        <a class="btn btn-raised btn-default btn-xs purple" href="{{ path('ledger_edit', { 'id': ledger.id }) }}">Edit</a>
                                {% endif %}
                                </td>
                            {% endif %}
                        </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

src/OrderBundle/Resources/views/Ledger/new.html.twig
{% extends ':default:layout.html.twig' %}

{% block title %}New Ledger Fund Request{% endblock %}
{% block page_title %}New Ledger Fund Request{% endblock page_title %}

{% block page_name %}
    <a href="{{ path('ledger_index') }}">< Back to the list</a>
{% endblock page_name %}

{% block actions %}
{% endblock actions %}

{% block footer %}
    <script>
        $(document).ready(function () {
            $('#ledger_description').keyup(function () {
                var len = $(this).val().length;
                if (len >= 255) {
                    $(this).val($(this).val().substring(0, 255));
                    $('#charNum').text(0);
                } else {
                    var l = 255 - len;
                    $('#charNum').text(l);
                }
            });
        });
    </script>
{% endblock footer %}

{% block content %}
    {% if not form.vars.valid %}
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">
                    {{ form_errors(form.submittedForUser) }}
                    {{ form_errors(form.amountRequested) }}
                    {{ form_errors(form.description) }}
                </div>
            </div>
        </div>
    {% endif %}
    <div class="table">
        {% if app.user.achaccountnumber %}
        <div class="form-body">
            {{ form_start(form, {'attr': { 'class': 'form-horizontal' } }) }}
            <div class="row">
                <div class="col-md-3 form-group">
                    {{ form_label(form.amountRequested) }}
                    {{ form_widget(form.amountRequested) }}
                </div>
                {#<div class="col-md-3 form-group">#}
                    {#{{ form_label(form.phone) }}#}
                    {#{{ form_widget(form.phone) }}#}
                {#</div>#}
            </div>
            {#<div class="row">#}
                {#<div class="col-md-6 form-group">#}
                    {#{{ form_label(form.email) }}#}
                    {#{{ form_widget(form.email) }}#}
                {#</div>#}
            {#</div>#}
            {#<div class="row">#}
                {#<div class="col-md-6 form-group">#}
                    {#{{ form_label(form.description) }} <span id="charNum"#}
                                                             {#style="font-weight:200;color:#8e8e8e;">255</span>#}
                    {#{{ form_widget(form.description) }}#}
                {#</div>#}
            {#</div>#}
            <div class="row">
                <div class="col-md-12">
                    By submitting the form below, I authorize {{ app.user.activechannel.name }} to perform an ACH transfer on my behalf from the account ending in {{ app.user.achaccountnumber[-4:] }}.
                </div>
            </div>
            <input class="btn btn-raised btn-success" type="submit" value="Pay"/>
            {{ form_end(form) }}
        </div>
            {% else %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="danger">
                            You must have a valid ACH account setup in your <a href="{{ path('fos_user_profile_edit') }}">User Profile</a>.
                        </div>
                    </div>
                </div>
                {% endif %}
    </div>
{% endblock %}